import { supabase } from "@/app/lib/supabase";
import { CollectionFilters, RawCollectionResponse } from "@/app/lib/types/cards";
import GithubSlugger from "github-slugger";
import { toCollection } from "@/lib/utils";
type CollectionPayload = {
    id?: string;
    slug?: string;
    language: string;
    title: string;
    description: string;
    is_published: boolean;
    cards: {
        id?: string;
        word: string;
        reading: string;
        meaning: string;
    }[];
};
export const collectionService = {
    async getByUsername(username: string) {
        const { data, error } = await supabase
            .from("collections")
            .select("*, cards(count)")
            .eq("author_username", username)
            .order("created_at", { ascending: false });

        if (error) throw error;
        return (data as RawCollectionResponse[]).map(toCollection);
    },
    async getAllCollections(filters: CollectionFilters = {}) {
        let query = supabase
            .from("collections")
            .select("*, cards(count)")
            .eq("is_published", true)
            .order("created_at", { ascending: false });
        if (filters.language) query = query.eq("language", filters.language);
        if (filters.author) query = query.eq("author_username", filters.author);
        if (filters.searchTerm) query = query.ilike("title", `%${filters.searchTerm}%`);

        const { data, error } = await query;
        if (error) throw error;

        return (data as RawCollectionResponse[]).map(toCollection);
    },
    async getBySlug(slug: string) {
        const decodedSlug = decodeURIComponent(slug);
        const { data, error } = await supabase
            .from("collections")
            .select("*, cards(*)")
            .eq("slug", decodedSlug)
            .maybeSingle();

        if (error) throw error;
        return data;
    },
    async saveCollection(username: string, data: CollectionPayload) {
        if (data.id) {
            return this.updateCollection(username, data);
        }

        return this.createCollection(username, data);
    },
    async createCollection(username: string, data: CollectionPayload) {
        // 1. Generate the URL-friendly slug
        const slugger = new GithubSlugger();
        const slug =
            data.slug ||
            `${slugger.slug(data.title)}-${Math.floor(1000 + Math.random() * 9000)}`;

        // 2. Upsert the collection and SELECT the returned ID (UUID)
        const { data: collectionRow, error: colError } = await supabase
            .from("collections")
            .upsert({
                slug: slug, // Human-friendly Japanese/Text slug
                title: data.title,
                language: data.language,
                description: data.description,
                author_username: username,
                is_published: data.is_published,
            }, {
                onConflict: 'slug' // If a collection with this slug exists, update it
            })
            .select("id") // CRITICAL: This retrieves the UUID generated by Postgres
            .single();

        if (colError) throw colError;
        if (!collectionRow) throw new Error("Failed to retrieve collection ID");

        const collectionUuid = collectionRow.id;
        // 3. Map cards to the UUID
        const cardsToInsert = data.cards.map((card, index) => ({
            collection_id: collectionUuid, // Use the UUID here!
            word: card.word,
            reading: card.reading,
            meaning: card.meaning,
            order_index: index,
        }));

        // 5. Insert new cards
        const { error: cardError } = await supabase.from("cards").insert(cardsToInsert);
        if (cardError) throw cardError;

        // Return the slug so the frontend can redirect to the correct URL
        return slug;
    },

    async updateCollection(
        username: string,
        data: CollectionPayload
    ) {
        if (!data.id) throw new Error("Collection id is required");

        const { error: collectionError } = await supabase
            .from("collections")
            .update({
                title: data.title,
                slug: data.slug,
                language: data.language,
                description: data.description,
                author_username: username,
                is_published: data.is_published,
            })
            .eq("id", data.id);

        if (collectionError) throw collectionError;

        const { data: existingCards, error: fetchError } =
            await supabase
                .from("cards")
                .select("id")
                .eq("collection_id", data.id);

        if (fetchError) throw fetchError;

        const incomingIds = new Set(
            data.cards
                .filter((c) => c.id)
                .map((c) => c.id)
        );

        const toDelete = existingCards
            .filter((c) => !incomingIds.has(c.id))
            .map((c) => c.id);

        if (toDelete.length) {
            const { error } = await supabase
                .from("cards")
                .delete()
                .in("id", toDelete);

            if (error) throw error;
        }

        const cardsToUpsert = data.cards.map(
            (card, index) => ({
                id: card.id,
                collection_id: data.id,
                word: card.word,
                reading: card.reading,
                meaning: card.meaning,
                order_index: index,
            })
        );

        const { error: cardError } = await supabase
            .from("cards")
            .upsert(cardsToUpsert);

        if (cardError) throw cardError;

        return data.slug;
    },
    async deleteCollection(slug: string) {
        const decodedSlug = decodeURIComponent(slug);
        const { error } = await supabase
            .from("collections")
            .delete()
            .eq("slug", decodedSlug);
        if (error) throw error;
    }
};