import { supabase } from "@/app/lib/supabase";
import { CollectionFilters, RawCollectionResponse } from "@/app/lib/types";
import { toCollection } from "@/lib/utils";

export const collectionService = {
    async getByUsername(username: string) {
        const { data, error } = await supabase
            .from("collections")
            .select("*, cards(count)")
            .eq("author_username", username)
            .order("created_at", { ascending: false });

        if (error) throw error;
        return (data as RawCollectionResponse[]).map(toCollection);
    },
    async getAllCollections(filters: CollectionFilters = {}) {
        let query = supabase
            .from("collections")
            .select("*, cards(count)")
            .eq("is_published", true)
            .order("created_at", { ascending: false });
        if (filters.language) query = query.eq("language", filters.language);
        if (filters.author) query = query.eq("author_username", filters.author);
        if (filters.searchTerm) query = query.ilike("title", `%${filters.searchTerm}%`);

        const { data, error } = await query;
        if (error) throw error;

        return (data as RawCollectionResponse[]).map(toCollection);
    },
    async getBySlug(slug: string) {
        const decodedSlug = decodeURIComponent(slug);
        const { data, error } = await supabase
            .from("collections")
            .select("*, cards(*)")
            .eq("slug", decodedSlug)
            .maybeSingle();

        if (error) throw error;
        return data;
    },
    async saveCollection(
        username: string,
        data: {
            id?: string;
            slug?: string;
            language: string;
            title: string;
            description: string;
            is_published: boolean;
            cards: { word: string; reading: string; meaning: string }[];
        }
    ) {
        // 1. Generate the URL-friendly slug
        const slug = data.slug ||
            `${data.title.toLowerCase().trim().replace(/\s+/g, "-")}-${Math.floor(1000 + Math.random() * 9000)}`;

        // 2. Upsert the collection and SELECT the returned ID (UUID)
        const { data: collectionRow, error: colError } = await supabase
            .from("collections")
            .upsert({
                slug: slug, // Human-friendly Japanese/Text slug
                title: data.title,
                language: data.language,
                description: data.description,
                author_username: username,
                is_published: data.is_published,
            }, {
                onConflict: 'slug' // If a collection with this slug exists, update it
            })
            .select("id") // CRITICAL: This retrieves the UUID generated by Postgres
            .single();

        if (colError) throw colError;
        if (!collectionRow) throw new Error("Failed to retrieve collection ID");

        const collectionUuid = collectionRow.id;
        // 3. Map cards to the UUID
        const cardsToInsert = data.cards.map((card, index) => ({
            collection_id: collectionUuid, // Use the UUID here!
            word: card.word,
            reading: card.reading,
            meaning: card.meaning,
            order_index: index,
        }));

        // 5. Insert new cards
        const { error: cardError } = await supabase.from("cards").insert(cardsToInsert);
        if (cardError) throw cardError;

        // Return the slug so the frontend can redirect to the correct URL
        return slug;
    },
    async deleteCollection(slug: string) {
        const decodedSlug = decodeURIComponent(slug);
        const { error } = await supabase
            .from("collections")
            .delete()
            .eq("slug", decodedSlug);
        if (error) throw error;
    }
};